"""
Django settings for norloc project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.core.management.utils import get_random_secret_key

env = environ.Env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR / ".env.development"

if os.path.isfile(ENV_FILE):
    print(f"Using env file {ENV_FILE}")
    env.read_env(env_file=str(ENV_FILE))

SECRET_KEY = env.str('DJANGO_SECRET_KEY', get_random_secret_key())
DEBUG = env.bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")
CORS_ALLOW_ALL_ORIGINS = DEBUG
SITE_URL = env.str("DJANGO_SITE_URL")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    
    'corsheaders',
    'leaflet',
    'leaflet_admin_list',
    'rest_framework',
    'rest_framework_gis',
    'django_fullclean',
    'sorl.thumbnail',
    'drf_yasg',
    'markdownfield',

    'productions',
    'locations',
    'people',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'norloc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'norloc.wsgi.application'


# Database
#  https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ['POSTGRES_DATABASE'],
        'USER': os.environ['POSTGRES_USER'],
        'PASSWORD': os.environ['POSTGRES_PASSWORD'],
        'HOST': os.environ['POSTGRES_HOST'],
        'PORT': os.environ['POSTGRES_PORT'],
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
#  https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# REST framework
#  https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    # 'EXCEPTION_HANDLER': 'common.exceptions.exception_handler',
    #  'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.BasicAuthentication',
    #     'rest_framework.authentication.SessionAuthentication',
    # ]
}


# Internationalization
#  https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Oslo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
#  https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = BASE_DIR / 'static'
STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'


# Leaflet
#  https://github.com/makinacorpus/django-leaflet
#  https://github.com/nnseva/django-leaflet-admin-list

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (59.912756, 10.734347),
    'DEFAULT_ZOOM': 12,
    # 'MAX_ZOOM': 20,
    # 'MIN_ZOOM': 3,
    'SCALE': 'both',
    'TILES': [
        (
            'Kartverket (gråtone)',
            'https://opencache.statkart.no/gatekeeper/gk/gk.open_gmaps?layers=topo4graatone&zoom={z}&x={x}&y={y}',
            {'attribution': '&copy; Kartverket', 'maxZoom': 25},
        ),
        (
            'OSM',
            'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            {'attribution': '&copy; OpenStreetMap'},
        ),
        (
            '1881',
            'https://waapi.webatlas.no/maptiles/tiles/webatlas-1881-vektor/wa_grid/{z}/{x}/{y}.png?APITOKEN=9da664c7-e5b9-4dc7-a093-7ef0f90563c0',
            {'attribution': '&copy; 1881'}
        ),
    ]
}

LEAFLET_ADMIN_LIST = {
    'line_style': {
        'color': '#3388ff',
        'fillColor': '#3388ff',
        'fillOpacity': 0.2,
    }
}


# Markdown
#  https://github.com/dmptrluke/django-markdownfield
#  https://python-markdown.github.io/extensions/

MARKDOWN_EXTENSIONS = ['common.markdown_ext:UniqueFootnoteExtension']
